Di 1112 exomiser ranking fix
eastgenomics/eggd_generate_rd_wgs_workbook pull request #11
Opened 2024-09-02 09:38 UTC by kjwinfield

Correct issue where variants in GEL tiering page could be duplicated onto exomiser tiering page.
Prev version shows variants ranked 1, 2, and 3
![image](https://github.com/user-attachments/assets/fc80b346-0e68-4c24-a1f9-500c7b08189e)
although 2 and 3 are already in GEL tiering page

New versions shows 1, 5, and 8, which is correct:
![image](https://github.com/user-attachments/assets/649d043e-3273-4fad-a96a-dfc094c8841e)

2024-09-02 09:38 UTC, pep8speaks commented
Hello @kjwinfield! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`resources/home/dnanexus/make_workbook.py`](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/52d59760b9eda3a40c0c12292fc40916a6d45488/resources/home/dnanexus/make_workbook.py):

> [Line 806:47](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/52d59760b9eda3a40c0c12292fc40916a6d45488/resources/home/dnanexus/make_workbook.py#L806): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 815:18](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/52d59760b9eda3a40c0c12292fc40916a6d45488/resources/home/dnanexus/make_workbook.py#L815): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2024-09-02 14:28 UTC, Addy81 requested changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @kjwinfield)

___
*[`resources/home/dnanexus/get_variant_info.py` line 349 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11#-O5n49HsDBHBhvcEolm_:-O5n49HsDBHBhvcEolma:beo9j8g) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/52d59760b9eda3a40c0c12292fc40916a6d45488/resources/home/dnanexus/get_variant_info.py#L349)):*
> ```Python
>         top = []
> 
>         ordered_list = dict(sorted(ranked.items(), key=lambda item: item[1]))
> ```

this is not a list if you are casting it back to a dict? 

Could you also add some comments in this function. I'm struggling to visualise what the input dict is. Could you add an example in your docstring and some comments to explain your logic?
___
*[`resources/home/dnanexus/make_workbook.py` line 801 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11#-O5n77BS9ioDoHjFu20-:-O5n77BS9ioDoHjFu200:b8j0ehs) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/52d59760b9eda3a40c0c12292fc40916a6d45488/resources/home/dnanexus/make_workbook.py#L801)):*
> ```Python
>             # columns ending _x)
>             d = {}
>             for col in self.var_df.columns:
> ```

I think you can skip some of this by setting suffices in your colum so it only renames one then you can drop the other if you don't want it: 

![image.png](https://files.reviewableusercontent.io/images/reviewable/33088252/f9iRsGedg_U1iYO3VAPyjFbn/image.png)
___
*[`resources/home/dnanexus/make_workbook.py` line 816 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11#-O5n7UuoBShr9oQMshol:-O5n7UuoBShr9oQMshom:b-oj481h) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/52d59760b9eda3a40c0c12292fc40916a6d45488/resources/home/dnanexus/make_workbook.py#L816)):*
> ```Python
>             ranks = ex_df['Priority'].to_dict()
>             for k,v in ranks.items():
>                 ranks[k] = int(v.split(' ')[-1].split('.')[0])
> ```

why is this needed? is this {index: int(exomiser rank)} the ranks dict when first created or the intended dict?


<!-- Sent from Reviewable.io -->

2024-09-02 15:53 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @Addy81)

___
*[`resources/home/dnanexus/get_variant_info.py` line 349 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11#-O5n49HsDBHBhvcEolm_:-O5nQjLEBuNfbZi5AK8Z:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/52d59760b9eda3a40c0c12292fc40916a6d45488/resources/home/dnanexus/get_variant_info.py#L349)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

this is not a list if you are casting it back to a dict? 

Could you also add some comments in this function. I'm struggling to visualise what the input dict is. Could you add an example in your docstring and some comments to explain your logic?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/make_workbook.py` line 801 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11#-O5n77BS9ioDoHjFu20-:-O5nQpcVBM8VUcBY8X8X:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/52d59760b9eda3a40c0c12292fc40916a6d45488/resources/home/dnanexus/make_workbook.py#L801)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

I think you can skip some of this by setting suffices in your colum so it only renames one then you can drop the other if you don't want it: 

![image.png](https://files.reviewableusercontent.io/images/reviewable/33088252/f9iRsGedg_U1iYO3VAPyjFbn/image.png)
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/make_workbook.py` line 816 at r1](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11#-O5n7UuoBShr9oQMshol:-O5nQqICCyZuLxKWUD-c:b-fdcafl) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/52d59760b9eda3a40c0c12292fc40916a6d45488/resources/home/dnanexus/make_workbook.py#L816)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

why is this needed? is this {index: int(exomiser rank)} the ranks dict when first created or the intended dict?
</blockquote></details>

Done. hopefully this explains it better. the current df has "Exomiser Rank 1.0" when we just want the integer to pass to get_top_3_ranked which expects a dict of {index in df: integer denoting rank}


<!-- Sent from Reviewable.io -->

2024-09-12 16:13 UTC, Addy81 requested changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @kjwinfield)

___
*[`resources/home/dnanexus/get_variant_info.py` line 389 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11#-O6azvUSB5r_rBDJ9LG2:-O6azvUSB5r_rBDJ9LG3:b8fdm6a) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/47cf9850d9cfc5abd8941cacc1c79300bab5a474/resources/home/dnanexus/get_variant_info.py#L389)):*
> ```Python
>                 else:
>                     break
>         return top
> ```

if not returning top, the docstring feels now to not match the function? 

if you don't need gold silver and bronze anymore, could this be done with a df and a sort/select values out instead of all the if statements?


<!-- Sent from Reviewable.io -->

2024-09-12 16:14 UTC, Addy81 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @kjwinfield)

___
*[`resources/home/dnanexus/get_variant_info.py` line 389 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11#-O6azvUSB5r_rBDJ9LG2:-O6b-ruo8XSsORi_Yswx:b-y1fbor) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/47cf9850d9cfc5abd8941cacc1c79300bab5a474/resources/home/dnanexus/get_variant_info.py#L389)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

if not returning top, the docstring feels now to not match the function? 

if you don't need gold silver and bronze anymore, could this be done with a df and a sort/select values out instead of all the if statements?
</blockquote></details>

Sorry that was meant to say if only returning top


<!-- Sent from Reviewable.io -->

2024-09-16 12:32 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @Addy81)

___
*[`resources/home/dnanexus/get_variant_info.py` line 389 at r3](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11#-O6azvUSB5r_rBDJ9LG2:-O6uKYc-8PCVPbeINTuZ:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/47cf9850d9cfc5abd8941cacc1c79300bab5a474/resources/home/dnanexus/get_variant_info.py#L389)):*
<details><summary><i>Previously, Addy81 (Adriana) wrote…</i></summary><blockquote>

Sorry that was meant to say if only returning top
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-09-16 13:23 UTC, jethror1 requested changes
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @Addy81 and @kjwinfield)

___
*[`resources/home/dnanexus/get_variant_info.py` line 348 at r4](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11#-O6uw4y2E5-T34j1NnGa:-O6uw4y2E5-T34j1NnGb:b-pvvb4u) ([raw file](https://github.com/eastgenomics/eggd_generate_rd_wgs_workbook/blob/f2f907ac893dfb3228f7abb08aba8d50b2a728d9/resources/home/dnanexus/get_variant_info.py#L348)):*
> ```Python
>         df = df.copy()
>         # First change "Exomiser Rank #" string to int
>         df['Priority'] = df['Priority'].map(
> ```

I would generally avoid modifying your underlying data and then trying to return its state, and just create a new column that you can drop at the end, something like:
```
df['priority_as_int'] = df['Priority'].map(
       lambda x: int(x.split(' ')[-1].split('.')[0])
    )

...

df.drop(['priority_as_int'], axis=1, inplace=True)
```



_Code quote:_
```Python
        # First change "Exomiser Rank #" string to int
        df['Priority'] = df['Priority'].map(
```


<!-- Sent from Reviewable.io -->

2024-09-16 14:56 UTC, jethror1 approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_generate_rd_wgs_workbook/11)* status: all files reviewed, 5 unresolved discussions (waiting on @Addy81 and @kjwinfield)



<!-- Sent from Reviewable.io -->

2024-09-16 14:56 UTC, merged